default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: CoinExchange_development

test:
  <<: *default
  database: CoinExchange_test

production:
  <<: *default
  database: CoinExchange_production
  username: CoinExchange
  password: <%= ENV['COINEXCHANGE_DATABASE_PASSWORD'] %>
